### ISSUE TITLE
Stripe integration failed

### ISSUE THREAD

**Issue by dsapoetra** [wasp-lang/open-saas#247]
Hi, I tried to setup with stripe in my local, but eventhough I use these as configs:

```
STRIPE_KEY=sk_test_51<the rest>
# to create a test product, go to https://dashboard.stripe.com/test/products and click on + Add Product
STRIPE_HOBBY_SUBSCRIPTION_PRICE_ID=prod_Qa<the rest>
STRIPE_PRO_SUBSCRIPTION_PRICE_ID=prod_QawjJ<the rest>
STRIPE_CREDITS_PRICE_ID=prod_Qawjs<the rest>
# after downloading starting the stripe cli (https://stripe.com/docs/stripe-cli) with `stripe listen --forward-to localhost:3001/stripe-webhook` it will output your signing secret
STRIPE_WEBHOOK_SECRET=whsec_e7f0<the rest>
```

I still got:
```
[ Server ] POST /operations/generate-stripe-checkout-session 400 806.257 ms - 549
[ Server!] Error: No such price: 'prod_Qa<the rest>'
[ Server!]     at StripeError.generate (file:///Users/metranet/fullstack/trial/app/node_modules/stripe/esm/Error.js:7:20)
[ Server!]     at res.toJSON.then.StripeAPIError.message (file:///Users/metranet/fullstack/trial/app/node_modules/stripe/esm/RequestSender.js:102:43)
[ Server!]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

How to setup the stripe or configure the config?

Thanks before ...

**Comment by dsapoetra** [comment]
That works like a charm! Thanks @frontier777 ! :D
