### ISSUE TITLE
Add Flask to the Open Saas

### ISSUE THREAD

**Issue by danjeldurmo** [wasp-lang/open-saas#41]
Hi, maybe my issue will be useful to others users.
I'm trying to implement Flask in the backend to get some financial information thanks to a python library.

**main.wasp**
```css
route FinanceRoute { path: "/finance", to: FinancePage }
page FinancePage {
  authRequired: true,
  component: import FinancePage from "@client/app/FinancePage"
}

query getStockInfo {
  fn: import { getStockInfo } from "@server/queries.js"
} 
```

**src/server/queries.ts**
```ts
import axios from 'axios';

export const getStockInfo = async ({ symbol }) => {
  console.log("getStockInfo called with symbol:", symbol); // Log del simbolo in ingresso
  try {
      const response = await axios.post('http://localhost:5000/getStockInfo', { symbol });
      console.log("Response from Flask server:", response.data); // Log della risposta dal server Flask
      return response.data.longName;
  } catch (error) {
      console.error("Error calling Flask server:", error.message); // Log dell'errore, se presente
      throw new HttpError(500, error.response ? error.response.data.error : "Server error");
  }
};
```

**src/server/finance_server.py**
```py
from flask import Flask, request, jsonify
from flask_cors import CORS
import yfinance as yf

app = Flask(__name__)
CORS(app)

@app.route('/getStockInfo', methods=['POST'])
def get_stock_info():
    data = request.json
    print("Dati ricevuti:", data)  # Logging dei dati ricevuti
    symbol = data.get('symbol')
    if not symbol:
        return jsonify({'error': 'Missing symbol parameter'}), 400
    try:
        stock = yf.Ticker(symbol)
        info = stock.info
        return jsonify({'longName': info.get('longName', 'Name not found')})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)
```

**src/client/FinancePage.tsx**
```tsx
import React, { useState } from 'react';
import { useQuery } from '@wasp/queries';
import getStockInfo from '@wasp/queries/getStockInfo';

const FinancePage = () => {
  const [inputSymbol, setInputSymbol] = useState('');
  const [longName, setLongName] = useState('');
  const [error, setError] = useState('');

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!inputSymbol) {
        console.error("Symbol is undefined or empty");
        setError("Symbol is undefined or empty");
        return;
    }
    try {
      const name = await getStockInfo({ symbol: inputSymbol });
      setLongName(name);
      setError('');
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div>
      <form onSubmit={handleSearch}>
        <input
          type="text"
          value={inputSymbol}
          onChange={(e) => setInputSymbol(e.target.value)}
        />
        <button type="submit">Get Stock Info</button>
      </form>
      {longName && <p>Long Name: {longName}</p>}
      {error && <p>Error: {error}</p>}
    </div>
  );
};

export default FinancePage;

```

But i retrive this error:

**[Server!] Error calling Flask server: Request failed with status code 403
[Server]  POST /operations/get-stock-info 500 12.396 ms - 14**

![Screenshot 2024-02-13 alle 14 34 55](https://github.com/wasp-lang/open-saas/assets/66755329/bea1ba07-35a0-43b2-800c-52909a74023b)

Surely there is a communication problem between the server and flask, would anyone know how to solve it?

**Comment by danjeldurmo** [comment]
On terminal work well:

`(base) danjeldurmo@Air-di-Danjel ~ % curl -X POST http://localhost:5000/getStockInfo -H "Content-Type: application/json" -d '{"symbol":"AAPL"}'

{
  "longName": "Apple Inc."
}`

**Comment by Martinsos** [comment]
Hm this is quite weird!

I doubt this is connected to Wasp. What I would potentially try is running a simple axios call from a nodejs script, meaning you would create a `test.js` file, import axios in it, do a very simple call (same one you did from your wasp app), and then run that with `node test.js`. If that has the same issue, then we can focus on that simpler code, if not, we go back to investigating issue in the context of Wasp app.

What I am mostly suspicious about is CORS. Call is obviously going from the Wasp server to python app, since response is 403: `The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.` -> it means your flask app received that request, but decided the request is not authorized. 
When doing a request via CURL, CORS is usually observed differently, which is why that might have worked.

Btw, when you get error via call from Wasp, does your Flask app print anything? Does it get to that line `print("Dati ricevuti:", data)` and print something?

**Comment by bababuluba** [comment]
what i actually want to do is to create a reverse proxy to the request on a route to my internal docker service like:
`const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');
const app = express();
const port = 3000;

// Basic route
app.get('/', (req, res) => {
  res.send('Hello, this is your Node.js app!');
});

// Proxy route to Docker service
app.use('/docker-service', createProxyMiddleware({ target: 'http://docker-service-host:docker-service-port', changeOrigin: true }));

app.listen(port, () => {
  console.log(`Node.js app listening at http://localhost:${port}`);
});
`

**Comment by danjeldurmo** [comment]
Hi @Martinsos thanks for your time.
I did what you told me and the result was this:

```
(base) danjeldurmo@Air-di-Danjel server % node test.js
getStockInfo called with symbol: AAPL
Error calling Flask server: 
Caught Error: Error
    at getStockInfo (/Users/danjeldurmo/Desktop/open-saas/app/src/server/test.js:13:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I have no idea how to fix.
Here bellow more detail abot error:
```
(base) danjeldurmo@Air-di-Danjel server % node test.js
getStockInfo called with symbol: AAPL
Error calling Flask server: AxiosError: Request failed with status code 403
    at settle (/Users/danjeldurmo/Desktop/open-saas/app/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/Users/danjeldurmo/Desktop/open-saas/app/node_modules/axios/dist/node/axios.cjs:3066:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/Users/danjeldurmo/Desktop/open-saas/app/node_modules/axios/dist/node/axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStockInfo (/Users/danjeldurmo/Desktop/open-saas/app/src/server/test.js:6:24) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.6.7',
      'Content-Length': '17',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://localhost:5000/getStockInfo',
    data: '{"symbol":"AAPL"}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '17',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 6,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /getStockInfo HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.6.7\r\n' +
      'Content-Length: 17\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: localhost:5000\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/getStockInfo',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://localhost:5000/getStockInfo',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 4,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 17,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://localhost:5000/getStockInfo',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: Object [AxiosHeaders] {
      'content-length': '0',
      server: 'AirTunes/665.13.1'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'http://localhost:5000/getStockInfo',
      data: '{"symbol":"AAPL"}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '17',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /getStockInfo HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.6.7\r\n' +
        'Content-Length: 17\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:5000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/getStockInfo',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  }
}
Detailed error: 
Caught Error: Error: Server error
    at getStockInfo (/Users/danjeldurmo/Desktop/open-saas/app/src/server/test.js:13:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by danjeldurmo** [comment]
Habemus papa! I managed to solve the issue:

```
(base) danjeldurmo@Air-di-Danjel server % node test.js
getStockInfo called with symbol: AAPL
Response from Flask server: { longName: 'Apple Inc.' }
Long Name: Apple Inc.
```
Simply replace localhost with http://127.0.0.1:5001/getStockInfo and server begin running
```
const response = await axios.post('http://127.0.0.1:5001/getStockInfo', { symbol });
```

**Comment by Martinsos** [comment]
@danjeldurmo great! Ok, so switching from `http://localhost:5001/getStockInfo` to `http://127.0.0.1:5001/getStockInfo` fixed the problem. But you also changed the port, from `5000` to `5001`, right? Maybe that was part of the issue?
So this is certainly not a CORS error then, instead it was your Flask server rejecting the request for some reason.
